FROM debian:bullseye
RUN /bin/bash

ARG OOMMF_DOWNLOAD_URL=https://math.nist.gov/oommf/dist/oommf20a3_20210930.tar.gz

# Avoid asking for geographic data when installing tzdata.
# ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update
RUN apt-get -y install wget
RUN apt-get install -y tcl-dev tk-dev git


# OOMMF cannot be built as root user.
RUN adduser user
USER user
WORKDIR /home/user

# Fetch OOMMf (from NIST)
RUN wget $OOMMF_DOWNLOAD_URL
RUN tar xfz oommf20a3_20210930.tar.gz
WORKDIR /home/user/oommf

# Compile OOMMF according to Readme
RUN ./oommf.tcl pimake +platform > pimake-platform-output.txt
RUN ./oommf.tcl pimake distclean
RUN ./oommf.tcl pimake upgrade
RUN ./oommf.tcl pimake

# Create test:
RUN echo "tclsh oommf.tcl boxsi +fg app/oxs/examples/stdprob3.mif -kill all" > run-test.sh
# execute test (takes about 14 seconds on 2 threads)
RUN sh run-test.sh

RUN ./oommf.tcl +version

CMD /bin/bash
