name: debian-spack-v0.18.1

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make oommf-spack-v0.18.1 
      
