name: debian-spack-develop

on:
  # Trigger the workflow on push or pull request,
  # but only for the spack-develop branch
  push:
    branches:
      - spack-develop
  pull_request:
    branches:
      - spack-develop
  schedule:
    # also run periodically
    - cron: "3 0 * * 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make oommf-spack
