name: osx-spack-develop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install GitHub CLI
        run: |
          brew update
          brew install gh
      - name: install spack
        run: |
          git clone https://github.com/fangohr/oommf
          cd oommf
          git checkout upgrade-2.0a2
          cat oommf-version
      - name: compile oommf
        run: |
          pwd
          make build
      - name: run version and platform
        run: |
          tclsh oommf/oommf/.tcl +version
          tclsh oommf/oommf/.tcl +platform
      - name: run standard problem 3 directly
        run: |
          make test-all
